In [2]:
import selenium 
from selenium import webdriver
import pandas as pd 
from selenium.webdriver.common.by import By 
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
import time
from bs4 import BeautifulSoup
import requests
import warnings 
warnings.filterwarnings("ignore")

# ANS.1

In [12]:
driver = webdriver.Chrome()
driver.get("https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos")

In [37]:
table = driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]/tbody/tr/td')
all_table = []
for i in table:
    all_table.append(i.text)

In [38]:
all_table

['1.',
 '"Baby Shark Dance"[6]',
 "Pinkfong Baby Shark - Kids' Songs & Stories",
 '13.29',
 'June 17, 2016',
 '[A]',
 '2.',
 '"Despacito"[9]',
 'Luis Fonsi',
 '8.25',
 'January 12, 2017',
 '[B]',
 '3.',
 '"Johny Johny Yes Papa"[16]',
 "LooLoo Kids - Nursery Rhymes and Children's Songs",
 '6.78',
 'October 8, 2016',
 '',
 '4.',
 '"Bath Song"[17]',
 'Cocomelon - Nursery Rhymes',
 '6.38',
 'May 2, 2018',
 '',
 '5.',
 '"Shape of You"[18]',
 'Ed Sheeran',
 '6.07',
 'January 30, 2017',
 '[C]',
 '6.',
 '"See You Again"[21]',
 'Wiz Khalifa',
 '6.01',
 'April 6, 2015',
 '[D]',
 '7.',
 '"Wheels on the Bus"[26]',
 'Cocomelon - Nursery Rhymes',
 '5.53',
 'May 24, 2018',
 '',
 '8.',
 '"Phonics Song with Two Words"[27]',
 'ChuChu TV Nursery Rhymes & Kids Songs',
 '5.47',
 'March 6, 2014',
 '',
 '9.',
 '"Uptown Funk"[28]',
 'Mark Ronson',
 '5.02',
 'November 19, 2014',
 '',
 '10.',
 '"Learning Colors – Colorful Eggs on a Farm"[29]',
 'Miroshka TV',
 '4.96',
 'February 27, 2018',
 '',
 '11.',
 '"Gangnam Style"[30]',
 'officialpsy',
 '4.88',
 'July 15, 2012',
 '[E]',
 '12.',
 '"Masha and the Bear – Recipe for Disaster"[35]',
 'Get Movies',
 '4.56',
 'January 31, 2012',
 '',
 '13.',
 '"Dame Tu Cosita"[36]',
 'Ultra Records',
 '4.43',
 'April 5, 2018',
 '',
 '14.',
 '"Axel F"[37]',
 'Crazy Frog',
 '4.04',
 'June 16, 2009',
 '',
 '15.',
 '"Sugar"[38]',
 'Maroon 5',
 '3.93',
 'January 14, 2015',
 '',
 '16.',
 '"Counting Stars"[39]',
 'OneRepublic',
 '3.86',
 'May 31, 2013',
 '',
 '17.',
 '"Roar"[40]',
 'Katy Perry',
 '3.86',
 'September 5, 2013',
 '',
 '18.',
 '"Baa Baa Black Sheep"[41]',
 'Cocomelon - Nursery Rhymes',
 '3.76',
 'June 25, 2018',
 '',
 '19.',
 '"Waka Waka (This Time for Africa)"[42]',
 'Shakira',
 '3.71',
 'June 4, 2010',
 '',
 '20.',
 '"Sorry"[43]',
 'Justin Bieber',
 '3.70',
 'October 22, 2015',
 '',
 '21.',
 '"Lakdi Ki Kathi"[44]',
 'Jingle Toons',
 '3.67',
 'June 14, 2018',
 '',
 '22.',
 '"Thinking Out Loud"[45]',
 'Ed Sheeran',
 '3.65',
 'October 7, 2014',
 '',
 '23.',
 '"Dark Horse"[46]',
 'Katy Perry',
 '3.58',
 'February 20, 2014',
 '',
 '24.',
 '"Humpty the train on a fruits ride"[47]',
 'Kiddiestv Hindi - Nursery Rhymes & Kids Songs',
 '3.54',
 'January 26, 2018',
 '',
 '25.',
 '"Perfect"[48]',
 'Ed Sheeran',
 '3.53',
 'November 9, 2017',
 '',
 '26.',
 '"Faded"[49]',
 'Alan Walker',
 '3.51',
 'December 3, 2015',
 '',
 '27.',
 '"Let Her Go"[50]',
 'Passenger',
 '3.50',
 'July 25, 2012',
 '',
 '28.',
 '"Girls Like You"[51]',
 'Maroon 5',
 '3.47',
 'May 31, 2018',
 '',
 '29.',
 '"Lean On"[52]',
 'Major Lazer Official',
 '3.45',
 'March 22, 2015',
 '',
 '30.',
 '"Bailando"[53]',
 'Enrique Iglesias',
 '3.45',
 'April 11, 2014',
 '',
 '"Baby Shark Dance"[6]',
 "Pinkfong Baby Shark - Kids' Songs & Stories",
 '7,046,700,000',
 'June 17, 2016',
 'November 2, 2020',
 '1600',
 '1,045',
 '',
 '',
 '',
 '"Despacito"[9]',
 'Luis Fonsi',
 '2,993,700,000',
 'January 12, 2017',
 'August 4, 2017',
 '206',
 '1,186',
 '',
 '[65]',
 '[B]',
 '"See You Again"[21]',
 'Wiz Khalifa',
 '2,894,000,000',
 'April 6, 2015',
 'July 10, 2017',
 '826',
 '25',
 '',
 '[22]',
 '',
 '"Gangnam Style"⁂[30]',
 'Psy',
 '803,700,000',
 'July 15, 2012',
 'November 24, 2012',
 '134',
 '1,689',
 '',
 '[31]',
 '[E]',
 '"Baby"*[66]',
 'Justin Bieber',
 '245,400,000',
 'February 19, 2010',
 'July 16, 2010',
 '149',
 '862',
 '',
 '[67]',
 '[F]',
 '"Bad Romance"[70]',
 'Lady Gaga',
 '178,400,000',
 'November 24, 2009',
 'April 14, 2010',
 '143',
 '93',
 '',
 '[71]',
 '[G]',
 '"Charlie Bit My Finger"‡[74]',
 'HDCYT',
 '128,900,000',
 'May 22, 2007',
 'October 25, 2009',
 '887',
 '171',
 'late July 2021[75]',
 '[76]',
 '',
 '"Evolution of Dance"[77]',
 'Judson Laipply',
 '118,900,000',
 'April 6, 2006',
 'May 2, 2009',
 '1062',
 '176',
 '',
 '[78]',
 '',
 '"Girlfriend"‡[79][80]',
 'RCA Records',
 '92,600,000',
 'February 27, 2007',
 'July 17, 2008',
 '508',
 '289',
 'November 2009[81]',
 '[82]',
 '[H]',
 '"Evolution of Dance"[77]',
 'Judson Laipply',
 '78,400,000',
 'April 6, 2006',
 'March 15, 2008',
 '651',
 '124',
 '',
 '[84]',
 '',
 '"Music Is My Hot Hot Sex"‡[85]',
 'CLARUSBARTEL72',
 '76,600,000',
 'April 9, 2007',
 'March 1, 2008',
 '327',
 '14',
 'mid-2008[86]',
 '[87]',
 '[I]',
 '"Evolution of Dance"*[77]',
 'Judson Laipply',
 '10,600,000',
 'April 6, 2006',
 'May 19, 2006',
 '16',
 '652',
 '',
 '[90]',
 '[J]',
 '"Pokémon Theme Music Video"‡[91]',
 'Smosh',
 '4,300,000',
 'November 28, 2005',
 'March 12, 2006',
 '105',
 '68',
 'June 2007[92]',
 '[93]',
 '[K]',
 '"Myspace – The Movie"‡[96][97]',
 'eggtea',
 '2,700,000',
 'January 31, 2006',
 'February 18, 2006',
 '18',
 '22',
 'mid-2006[98]',
 '[99]',
 '',
 '"Phony Photo Booth"‡[100]',
 'mugenized',
 '3,400,000',
 'December 1, 2005',
 'January 21, 2006',
 '50',
 '28',
 'no data',
 '[101]',
 '[L]',
 '"The Chronic of Narnia Rap"‡[102]',
 'youtubedude',
 '2,300,000',
 'December 18, 2005',
 'January 9, 2006',
 '22',
 '12',
 'no data',
 '[103]',
 '',
 '"Cross Bar"‡[104]',
 'joeB',
 '1,000,000',
 'October 21, 2005',
 'December 10, 2005',
 '50',
 '30',
 'no data',
 '[105][104]',
 '',
 '"Ronaldinho: Touch of Gold"‡*[106]',
 'Nikesoccer',
 '255,000',
 'October 21, 2005',
 'October 31, 2005',
 '10',
 '40',
 'no data',
 '[107]',
 '[M]',
 '"I/O Brush"‡*[109]',
 'larfus',
 '247,000',
 'October 5, 2005',
 'October 29, 2005',
 '24',
 '2',
 'January to April 2007[110]',
 '[111]',
 '',
 '"Me at the zoo"[112]',
 'jawed',
 '1',
 'April 23, 2005',
 'April 23, 2005',
 '0',
 '189',
 '',
 '[113]',
 '']

In [41]:
RANK=all_table[0::6]

VIDEO_NAME=all_table[1::6]

ARTIST=all_table[2::6]

VIEWS=all_table[3::6]

DATE=all_table[4:6]

# ANS.2

In [52]:
driver = webdriver.Chrome()
driver.get("https://www.bcci.tv/")

In [53]:
international =driver.find_element(By.XPATH,"/html/body/nav/div[1]/div[2]/ul[1]/li[2]/a")
international.click()

In [55]:
more =driver.find_element(By.XPATH,"/html/body/div[2]/div[2]/div/div/div/div[2]/div[3]/div[2]/div/button")
more.click()

In [57]:
Match_title = []



Match = driver.find_elements(By.XPATH,'//span[@class="matchOrderText ng-binding ng-scope"]')
for i in Match:
    data = i.text
    Match_title.append(data)
    
Match_title

['5th ODI -',
 'Final -',
 '1st T20I -',
 '1st ODI -',
 '2nd ODI -',
 '3rd ODI -',
 '1st ODI -',
 '1st T20I -',
 '2nd ODI -',
 '1st ODI -',
 '2nd ODI -',
 '3rd ODI -',
 '4th ODI -',
 '5th ODI -',
 '6th ODI -',
 '7th ODI -',
 '8th ODI -',
 '9th ODI -',
 '1st T20I -',
 '2nd T20I -',
 '3rd T20I -',
 '4th T20I -',
 '5th T20I -',
 '1st T20I -',
 '2nd T20I -',
 '3rd T20I -',
 '1st ODI -',
 '2nd ODI -',
 '3rd ODI -',
 '1st Test -',
 '2nd Test -',
 '1st T20I -',
 '2nd T20I -',
 '3rd T20I -',
 '1st Test -',
 '2nd Test -',
 '3rd Test -',
 '4th Test -',
 '5th Test -']

In [58]:
Series = []



Series_m = driver.find_elements(By.XPATH,'//h5[@class="match-tournament-name ng-binding"]')
for i in Series_m:
    data = i.text
    Series.append(data)
    
Series

['ASIA CUP 2023',
 'ASIA CUP 2023',
 '19TH ASIAN GAMES 2023',
 'AUSTRALIA TOUR OF INDIA 2023-24',
 'AUSTRALIA TOUR OF INDIA 2023-24',
 'AUSTRALIA TOUR OF INDIA 2023-24',
 'ICC MENS WORLD CUP 2023 WARM-UP MATCHES',
 '19TH ASIAN GAMES 2023',
 'ICC MENS WORLD CUP 2023 WARM-UP MATCHES',
 'ICC MENS WORLD CUP 2023',
 'ICC MENS WORLD CUP 2023',
 'ICC MENS WORLD CUP 2023',
 'ICC MENS WORLD CUP 2023',
 'ICC MENS WORLD CUP 2023',
 'ICC MENS WORLD CUP 2023',
 'ICC MENS WORLD CUP 2023',
 'ICC MENS WORLD CUP 2023',
 'ICC MENS WORLD CUP 2023',
 'AUSTRALIA TOUR OF INDIA 2023-24',
 'AUSTRALIA TOUR OF INDIA 2023-24',
 'AUSTRALIA TOUR OF INDIA 2023-24',
 'AUSTRALIA TOUR OF INDIA 2023-24',
 'AUSTRALIA TOUR OF INDIA 2023-24',
 'INDIA TOUR OF SOUTH AFRICA 2023-24',
 'INDIA TOUR OF SOUTH AFRICA 2023-24',
 'INDIA TOUR OF SOUTH AFRICA 2023-24',
 'INDIA TOUR OF SOUTH AFRICA 2023-24',
 'INDIA TOUR OF SOUTH AFRICA 2023-24',
 'INDIA TOUR OF SOUTH AFRICA 2023-24',
 'INDIA TOUR OF SOUTH AFRICA 2023-24',
 'INDIA TOUR OF SOUTH AFRICA 2023-24',
 'AFGHANISTAN TOUR OF INDIA 2023-24',
 'AFGHANISTAN TOUR OF INDIA 2023-24',
 'AFGHANISTAN TOUR OF INDIA 2023-24',
 'ENGLAND TOUR OF INDIA 2023-24',
 'ENGLAND TOUR OF INDIA 2023-24',
 'ENGLAND TOUR OF INDIA 2023-24',
 'ENGLAND TOUR OF INDIA 2023-24',
 'ENGLAND TOUR OF INDIA 2023-24']

In [59]:
Place = []



Place_m = driver.find_elements(By.XPATH,'//span[@class="ng-binding"]')
for i in Place_m:
    data = i.text
    Place.append(data)
    
Place

['Colombo',
 'Colombo',
 'Hangzhou',
 'Mohali',
 'Indore',
 'Rajkot',
 'Guwahati',
 'Hangzhou',
 'Thiruvananthapuram',
 'Chennai',
 'Delhi',
 'Ahmedabad',
 'Pune',
 'Dharamsala',
 'Lucknow',
 'Mumbai',
 'Kolkata',
 'Bengaluru',
 'Visakhapatnam',
 'Thiruvananthapuram',
 'Guwahati',
 'Nagpur',
 'Hyderabad',
 'Durban',
 'Gqeberha',
 'Johannesburg',
 'Johannesburg',
 'Gqeberha',
 'Paarl',
 'Centurion',
 'Cape Town',
 'Mohali',
 'Indore',
 'Bengaluru',
 'Hyderabad',
 'Visakhapatnam',
 'Rajkot',
 'Ranchi',
 'Dharamsala']

In [60]:
Date = []



Date_m = driver.find_elements(By.XPATH,'//div[@class="match-dates ng-binding"]')
for i in Date_m:
    data = i.text
    Date.append(data)
    
Date

['15 SEP 2023',
 '17 SEP 2023',
 '21 SEP 2023',
 '22 SEP 2023',
 '24 SEP 2023',
 '27 SEP 2023',
 '30 SEP 2023',
 '3 OCT 2023',
 '3 OCT 2023',
 '8 OCT 2023',
 '11 OCT 2023',
 '14 OCT 2023',
 '19 OCT 2023',
 '22 OCT 2023',
 '29 OCT 2023',
 '2 NOV 2023',
 '5 NOV 2023',
 '12 NOV 2023',
 '23 NOV 2023',
 '26 NOV 2023',
 '28 NOV 2023',
 '1 DEC 2023',
 '3 DEC 2023',
 '10 DEC 2023',
 '12 DEC 2023',
 '14 DEC 2023',
 '17 DEC 2023',
 '19 DEC 2023',
 '21 DEC 2023',
 '26 DEC 2023',
 '3 JAN 2024',
 '11 JAN 2024',
 '14 JAN 2024',
 '17 JAN 2024',
 '25 JAN 2024',
 '2 FEB 2024',
 '15 FEB 2024',
 '23 FEB 2024',
 '7 MAR 2024']

In [61]:
Time = []



Time_m = driver.find_elements(By.XPATH,'//div[@class="match-time no-margin ng-binding"]')
for i in Time_m:
    data = i.text
    Time.append(data)
    
Time

['3:00 PM IST',
 '3:00 PM IST',
 '6:30 AM IST',
 '1:30 PM IST',
 '1:30 PM IST',
 '1:30 PM IST',
 '2:00 PM IST',
 '6:30 AM IST',
 '2:00 PM IST',
 '2:00 PM IST',
 '2:00 PM IST',
 '2:00 PM IST',
 '2:00 PM IST',
 '2:00 PM IST',
 '2:00 PM IST',
 '2:00 PM IST',
 '2:00 PM IST',
 '2:00 PM IST',
 '7:00 PM IST',
 '7:00 PM IST',
 '7:00 PM IST',
 '7:00 PM IST',
 '7:00 PM IST',
 '9:30 PM IST',
 '9:30 PM IST',
 '9:30 PM IST',
 '2:00 PM IST',
 '2:00 PM IST',
 '2:00 PM IST',
 '1:30 PM IST',
 '1:30 PM IST',
 '7:00 PM IST',
 '7:00 PM IST',
 '7:00 PM IST',
 '9:30 AM IST',
 '9:30 AM IST',
 '9:30 AM IST',
 '9:30 AM IST',
 '9:30 AM IST']

In [63]:
df2 = pd.DataFrame({'Match_title':Match_title,'Series':Series,'Place':Place,'Date':Date,'Time':Time})
df2

,Match_title,Series,Place,Date,Time
0,5th ODI -,ASIA CUP 2023,Colombo,15 SEP 2023,3:00 PM IST
1,Final -,ASIA CUP 2023,Colombo,17 SEP 2023,3:00 PM IST
2,1st T20I -,19TH ASIAN GAMES 2023,Hangzhou,21 SEP 2023,6:30 AM IST
3,1st ODI -,AUSTRALIA TOUR OF INDIA 2023-24,Mohali,22 SEP 2023,1:30 PM IST
4,2nd ODI -,AUSTRALIA TOUR OF INDIA 2023-24,Indore,24 SEP 2023,1:30 PM IST
5,3rd ODI -,AUSTRALIA TOUR OF INDIA 2023-24,Rajkot,27 SEP 2023,1:30 PM IST
6,1st ODI -,ICC MENS WORLD CUP 2023 WARM-UP MATCHES,Guwahati,30 SEP 2023,2:00 PM IST
7,1st T20I -,19TH ASIAN GAMES 2023,Hangzhou,3 OCT 2023,6:30 AM IST
8,2nd ODI -,ICC MENS WORLD CUP 2023 WARM-UP MATCHES,Thiruvananthapuram,3 OCT 2023,2:00 PM IST
9,1st ODI -,ICC MENS WORLD CUP 2023,Chennai,8 OCT 2023,2:00 PM IST
10,2nd ODI -,ICC MENS WORLD CUP 2023,Delhi,11 OCT 2023,2:00 PM IST
11,3rd ODI -,ICC MENS WORLD CUP 2023,Ahmedabad,14 OCT 2023,2:00 PM IST
12,4th ODI -,ICC MENS WORLD CUP 2023,Pune,19 OCT 2023,2:00 PM IST
13,5th ODI -,ICC MENS WORLD CUP 2023,Dharamsala,22 OCT 2023,2:00 PM IST
14,6th ODI -,ICC MENS WORLD CUP 2023,Lucknow,29 OCT 2023,2:00 PM IST
15,7th ODI -,ICC MENS WORLD CUP 2023,Mumbai,2 NOV 2023,2:00 PM IST
16,8th ODI -,ICC MENS WORLD CUP 2023,Kolkata,5 NOV 2023,2:00 PM IST
17,9th ODI -,ICC MENS WORLD CUP 2023,Bengaluru,12 NOV 2023,2:00 PM IST
18,1st T20I -,AUSTRALIA TOUR OF INDIA 2023-24,Visakhapatnam,23 NOV 2023,7:00 PM IST
19,2nd T20I -,AUSTRALIA TOUR OF INDIA 2023-24,Thiruvananthapuram,26 NOV 2023,7:00 PM IST
20,3rd T20I -,AUSTRALIA TOUR OF INDIA 2023-24,Guwahati,28 NOV 2023,7:00 PM IST
21,4th T20I -,AUSTRALIA TOUR OF INDIA 2023-24,Nagpur,1 DEC 2023,7:00 PM IST
22,5th T20I -,AUSTRALIA TOUR OF INDIA 2023-24,Hyderabad,3 DEC 2023,7:00 PM IST
23,1st T20I -,INDIA TOUR OF SOUTH AFRICA 2023-24,Durban,10 DEC 2023,9:30 PM IST
24,2nd T20I -,INDIA TOUR OF SOUTH AFRICA 2023-24,Gqeberha,12 DEC 2023,9:30 PM IST
25,3rd T20I -,INDIA TOUR OF SOUTH AFRICA 2023-24,Johannesburg,14 DEC 2023,9:30 PM IST
26,1st ODI -,INDIA TOUR OF SOUTH AFRICA 2023-24,Johannesburg,17 DEC 2023,2:00 PM IST
27,2nd ODI -,INDIA TOUR OF SOUTH AFRICA 2023-24,Gqeberha,19 DEC 2023,2:00 PM IST
28,3rd ODI -,INDIA TOUR OF SOUTH AFRICA 2023-24,Paarl,21 DEC 2023,2:00 PM IST
29,1st Test -,INDIA TOUR OF SOUTH AFRICA 2023-24,Centurion,26 DEC 2023,1:30 PM IST
30,2nd Test -,INDIA TOUR OF SOUTH AFRICA 2023-24,Cape Town,3 JAN 2024,1:30 PM IST
31,1st T20I -,AFGHANISTAN TOUR OF INDIA 2023-24,Mohali,11 JAN 2024,7:00 PM IST
32,2nd T20I -,AFGHANISTAN TOUR OF INDIA 2023-24,Indore,14 JAN 2024,7:00 PM IST
33,3rd T20I -,AFGHANISTAN TOUR OF INDIA 2023-24,Bengaluru,17 JAN 2024,7:00 PM IST
34,1st Test -,ENGLAND TOUR OF INDIA 2023-24,Hyderabad,25 JAN 2024,9:30 AM IST
35,2nd Test -,ENGLAND TOUR OF INDIA 2023-24,Visakhapatnam,2 FEB 2024,9:30 AM IST
36,3rd Test -,ENGLAND TOUR OF INDIA 2023-24,Rajkot,15 FEB 2024,9:30 AM IST
37,4th Test -,ENGLAND TOUR OF INDIA 2023-24,Ranchi,23 FEB 2024,9:30 AM IST
38,5th Test -,ENGLAND TOUR OF INDIA 2023-24,Dharamsala,7 MAR 2024,9:30 AM IST

In [64]:
driver.close()

# ANS.3

In [4]:
driver = webdriver.Chrome()
driver.get("http://statisticstimes.com/")

In [6]:
econo =driver.find_element(By.XPATH,'//div[@class="navbar"]/div[2]')
econo.click()

In [7]:
india =driver.find_element(By.XPATH,'//div[@class="navbar"]/div[2]/div/a[3]')
india.click()

In [8]:
GDP_of_India_state =driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div[2]/ul/li[1]/a')
GDP_of_India_state.click()

In [12]:
Rank = []

title= driver.find_elements(By.XPATH,'//table[@class="display dataTable"]/tbody/tr/td[1]')
for i in title[0:33]:
    data = i.text
    Rank.append(data)

In [14]:
len(Rank)

33

In [15]:
State = []
GSDP_18_19 = []
GSDP_19_20 = []
Share_18_19 = []
GDP_billion = []

s= driver.find_elements(By.XPATH,'//table[@class="display dataTable"]/tbody/tr/td[2]')
for i in s[0:33]:
    data = i.text
    State.append(data)
    
g_18_19= driver.find_elements(By.XPATH,'//table[@class="display dataTable"]/tbody/tr/td[4]')
for i in g_18_19[0:33]:
    data = i.text
    GSDP_18_19.append(data)

    
    g_19_20= driver.find_elements(By.XPATH,'//table[@class="display dataTable"]/tbody/tr/td[3]')
for i in g_19_20[0:33]:
    data = i.text
    GSDP_19_20.append(data)    

    
    Sh_18_19= driver.find_elements(By.XPATH,'//table[@class="display dataTable"]/tbody/tr/td[5]')
for i in Sh_18_19[0:33]:
    data = i.text
    Share_18_19.append(data)    
    
billion= driver.find_elements(By.XPATH,'//table[@class="display dataTable"]/tbody/tr/td[6]')
for i in billion[0:33]:
    data = i.text
    GDP_billion.append(data)

In [16]:
df3 = pd.DataFrame({'Rank':Rank,'State':State,'GSDP(18-19)':GSDP_18_19,'GSDP(19-20)':GSDP_19_20,'Share(18-19)':Share_18_19,'GDP&billion':GDP_billion})
df3

,Rank,State,GSDP(18-19),GSDP(19-20),Share(18-19),GDP&billion
0,1,Maharashtra,"2,632,792",-,13.94%,399.921
1,2,Tamil Nadu,"1,630,208","1,845,853",8.63%,247.629
2,3,Uttar Pradesh,"1,584,764","1,687,818",8.39%,240.726
3,4,Gujarat,"1,502,899",-,7.96%,228.290
4,5,Karnataka,"1,493,127","1,631,977",7.91%,226.806
5,6,West Bengal,"1,089,898","1,253,832",5.77%,165.556
6,7,Rajasthan,"942,586","1,020,989",4.99%,143.179
7,8,Andhra Pradesh,"862,957","972,782",4.57%,131.083
8,9,Telangana,"861,031","969,604",4.56%,130.791
9,10,Madhya Pradesh,"809,592","906,672",4.29%,122.977
10,11,Kerala,"781,653",-,4.14%,118.733
11,12,Delhi,"774,870","856,112",4.10%,117.703
12,13,Haryana,"734,163","831,610",3.89%,111.519
13,14,Bihar,"530,363","611,804",2.81%,80.562
14,15,Punjab,"526,376","574,760",2.79%,79.957
15,16,Odisha,"487,805","521,275",2.58%,74.098
16,17,Assam,"315,881",-,1.67%,47.982
17,18,Chhattisgarh,"304,063","329,180",1.61%,46.187
18,19,Jharkhand,"297,204","328,598",1.57%,45.145
19,20,Uttarakhand,"245,895",-,1.30%,37.351
20,21,Jammu & Kashmir,"155,956",-,0.83%,23.690
21,22,Himachal Pradesh,"153,845","165,472",0.81%,23.369
22,23,Goa,"73,170","80,449",0.39%,11.115
23,24,Tripura,"49,845","55,984",0.26%,7.571
24,25,Chandigarh,"42,114",-,0.22%,6.397
25,26,Puducherry,"34,433","38,253",0.18%,5.230
26,27,Meghalaya,"33,481","36,572",0.18%,5.086
27,28,Sikkim,"28,723","32,496",0.15%,4.363
28,29,Manipur,"27,870","31,790",0.15%,4.233
29,30,Nagaland,"27,283",-,0.14%,4.144
30,31,Arunachal Pradesh,"24,603",-,0.13%,3.737
31,32,Mizoram,"22,287","26,503",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

# ANS.4

In [17]:
driver = webdriver.Chrome()
driver.get("https://github.com/")

In [18]:
open_source =driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/button')
open_source.click()

In [19]:
trending =driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/div/div[3]/ul/li[2]/a')
trending.click()

In [91]:
Repository_title = []



title= driver.find_elements(By.XPATH,'//h2[@class="h3 lh-condensed"]')
for i in title:
    data = i.text
    Repository_title.append(data)
    
Repository_title

['godotengine / godot',
 'rocketseat-education / nlw-ai-mastery',
 'tldraw / tldraw',
 'FL33TW00D / whisper-turbo',
 'lllyasviel / Fooocus',
 'dataelement / bisheng',
 'microsoft / azurechat',
 'turboderp / exllamav2',
 'TryQuiet / quiet',
 'tairov / llama2.mojo',
 'apna-college / Delta',
 'mylxsw / aidea',
 'OpenPipe / OpenPipe',
 'OpenBMB / AgentVerse',
 'guoyww / AnimateDiff',
 'DataTalksClub / machine-learning-zoomcamp',
 'krahets / hello-algo',
 'ianpatt / sfse',
 'laravel / framework',
 'steven-tey / dub',
 'Snoopy1866 / LiTiaotiao-Custom-Rules',
 'd2l-ai / d2l-zh',
 'microsoft / Web-Dev-For-Beginners',
 'facebook / react-native',
 'jedisct1 / libsodium']

In [84]:
Trending_url =[]
url = driver.find_elements(By.XPATH,'//a[@class="Link"]')
for i in url:
    Trending_url.append(i.get_attribute('href'))

In [92]:
Repository_description = []


for i in Trending_url:
    driver.get(i)
    time.sleep(1)
    
  
    
    try:
        title =driver.find_element(By.XPATH,'/html/body/div[1]/div[4]/div/main/turbo-frame/div/div/div/div[2]/div[2]/div/div[1]/div/p')
        Repository_description.append(title.text)
    except NoSuchElementException:
        Repository_description.append('Not present')
        
        
Repository_description

['Godot Engine – Multi-platform 2D and 3D game engine',
 'Not present',
 'a very good whiteboard',
 'Whisper on the web - turbocharged by your GPU 🏎️',
 'Focus on prompting and generating',
 'Bisheng is an open LLM devops platform for next generation AI applications.',
 '🤖 💼 Azure Chat Solution Accelerator powered by Azure Open AI Service',
 'A fast inference library for running LLMs locally on modern consumer-class GPUs',
 'A private, p2p alternative to Slack and Discord built on Tor & IPFS',
 'Inference Llama 2 in one file of pure 🔥',
 'Not present',
 'AIdea 是一款支持 GPT 以及国产大语言模型通义千问、文心一言等，支持 Stable Diffusion 文生图、图生图、 SDXL1.0、超分辨率、图片上色的全能型 APP。',
 'Turn expensive prompts into cheap fine-tuned models',
 '🤖 AgentVerse 🪐 provides a flexible framework that simplifies the process of building custom multi-agent environments for large language models (LLMs).',
 'Official implementation of AnimateDiff.',
 'The code from the Machine Learning Bookcamp book and a free course based on the book',
 '《Hello 算法》：动画图解、一键运行的数据结构与算法教程，支持 Java, C++, Python, Go, JS, TS, C#, Swift, Rust, Dart, Zig 等语言。',
 'Starfield Script Extender',
 'The Laravel Framework.',
 'An open-source link shortener with built-in analytics + free custom domains.',
 '李跳跳自定义规则',
 '《动手学深度学习》：面向中文读者、能运行、可讨论。中英文版被70多个国家的500多所大学用于教学。',
 '24 Lessons, 12 Weeks, Get Started as a Web Developer',
 'A framework for building native applications using React',
 'A modern, portable, easy to use crypto library.']

In [93]:
len(Repository_description)

25

In [83]:
Contributors_count = []



count= driver.find_elements(By.XPATH,'//div[@class="f6 color-fg-muted mt-2"]')
for i in count:
    data = i.text
    Contributors_count.append(data)
    
len(Contributors_count)

25

In [80]:
data1=Contributors_count
split_data = [element.split() for element in data1]


languages = [item[0] for item in split_data]
likes = [item[1] for item in split_data]

print(languages)
print(likes)

['C++', 'TypeScript', 'TypeScript', 'TypeScript', 'Python', 'Python', 'TypeScript', 'Python', 'C', 'Python', 'HTML', 'Dart', 'TypeScript', 'JavaScript', 'Python', 'Jupyter', 'Java', 'C++', 'PHP', 'TypeScript', 'Java', 'Python', 'JavaScript', 'Java', 'C']
['66,041', '172', '17,895', '431', '11,638', '460', '131', '883', '1,269', '727', '258', '4,502', '1,377', '1,323', '3,418', 'Notebook', '27,736', '216', '30,179', '11,756', '4,542', '47,758', '76,407', '111,857', '11,193']

In [81]:
len(languages)

25

In [82]:
len(likes)

25

In [94]:
df4 = pd.DataFrame({'Repository_title':Repository_title,'Repository_description':Repository_description,'languages':languages,'likes':likes})
df4

,Repository_title,Repository_description,languages,likes
0,godotengine / godot,Godot Engine – Multi-platform 2D and 3D game e...,C++,"66,041"
1,rocketseat-education / nlw-ai-mastery,Not present,TypeScript,172
2,tldraw / tldraw,a very good whiteboard,TypeScript,"17,895"
3,FL33TW00D / whisper-turbo,Whisper on the web - turbocharged by your GPU 🏎️,TypeScript,431
4,lllyasviel / Fooocus,Focus on prompting and generating,Python,"11,638"
5,dataelement / bisheng,Bisheng is an open LLM devops platform for nex...,Python,460
6,microsoft / azurechat,🤖 💼 Azure Chat Solution Accelerator powered by...,TypeScript,131
7,turboderp / exllamav2,A fast inference library for running LLMs loca...,Python,883
8,TryQuiet / quiet,"A private, p2p alternative to Slack and Discor...",C,"1,269"
9,tairov / llama2.mojo,Inference Llama 2 in one file of pure 🔥,Python,727
10,apna-college / Delta,Not present,HTML,258
11,mylxsw / aidea,AIdea 是一款支持 GPT 以及国产大语言模型通义千问、文心一言等，支持 Stable ...,Dart,"4,502"
12,OpenPipe / OpenPipe,Turn expensive prompts into cheap fine-tuned m...,TypeScript,"1,377"
13,OpenBMB / AgentVerse,🤖 AgentVerse 🪐 provides a flexible framework t...,JavaScript,"1,323"
14,guoyww / AnimateDiff,Official implementation of AnimateDiff.,Python,"3,418"
15,DataTalksClub / machine-learning-zoomcamp,The code from the Machine Learning Bookcamp bo...,Jupyter,Notebook
16,krahets / hello-algo,"《Hello 算法》：动画图解、一键运行的数据结构与算法教程，支持 Java, C++, P...",Java,"27,736"
17,ianpatt / sfse,Starfield Script Extender,C++,216
18,laravel / framework,The Laravel Framework.,PHP,"30,179"
19,steven-tey / dub,An open-source link shortener with built-in an...,TypeScript,"11,756"
20,Snoopy1866 / LiTiaotiao-Custom-Rules,李跳跳自定义规则,Java,"4,542"
21,d2l-ai / d2l-zh,《动手学深度学习》：面向中文读者、能运行、可讨论。中英文版被70多个国家的500多所大学用于教学。,Python,"47,758"
22,microsoft / Web-Dev-For-Beginners,"24 Lessons, 12 Weeks, Get Started as a Web Dev...",JavaScript,"76,407"
23,facebook / react-native,A framework for building native applications u...,Java,"111,857"
24,jedisct1 / libsodium,"A modern, portable, easy to use crypto library.",C,"11,193"

# ANS.5

In [95]:
driver = webdriver.Chrome()
driver.get("https:/www.billboard.com/")

In [96]:
three_line =driver.find_element(By.XPATH,'/html/body/div[3]/header/div/div[4]/div/div[1]/div[1]/button')
three_line.click()

In [97]:
hot_100 =driver.find_element(By.XPATH,'/html/body/div[3]/div[9]/div/div/div/ul/li[1]/ul/li[2]/a')
hot_100.click()

In [98]:
Song_name = []

name= driver.find_elements(By.XPATH,'//div[@class="o-chart-results-list-row-container"]')
for i in name:
    data = i.text
    Song_name.append(data)
    
Song_name

['1\nPaint The Town Red\nDoja Cat\n3\n1\n5',
 '2\nI Remember Everything\nZach Bryan Featuring Kacey Musgraves\n1\n1\n2',
 '3\nFast Car\nLuke Combs\n2\n2\n24',
 '4\nCruel Summer\nTaylor Swift\n5\n3\n18',
 '5\nLast Night\nMorgan Wallen\n4\n1\n32',
 '6\nDance The Night\nDua Lipa\n9\n6\n15',
 '7\nSnooze\nSZA\n7\n7\n39',
 '8\nFukumean\nGunna\n10\n4\n12',
 '9\nVampire\nOlivia Rodrigo\n12\n1\n10',
 '10\nCalm Down\nRema & Selena Gomez\n11\n3\n53',
 '11\nRich Men North Of Richmond\nOliver Anthony Music\n6\n1\n4',
 '12\nBarbie World\nNicki Minaj & Ice Spice With Aqua\n13\n7\n11',
 '13\nFlowers\nMiley Cyrus\n15\n1\n34',
 '14\nAll My Life\nLil Durk Featuring J. Cole\n16\n2\n17',
 '15\nReligiously\nBailey Zimmerman\n21\n14\n18',
 '16\nUsed To Be Young\nMiley Cyrus\n8\n8\n2',
 '17\nHey Driver\nZach Bryan Featuring The War And Treaty\n14\n14\n2',
 '18\nNeed A Favor\nJelly Roll\n26\n14\n23',
 "19\nThinkin' Bout Me\nMorgan Wallen\n34\n9\n27",
 '20\nAnti-Hero\nTaylor Swift\n32\n1\n46',
 '21\nKill Bill\nSZA\n27\n1\n39',
 '22\nWhat Was I Made For?\nBillie Eilish\n30\n14\n8',
 '23\nNEW\nLast Time I Saw You\nNicki Minaj\n-\n23\n1',
 '24\nKarma\nTaylor Swift Featuring Ice Spice\n25\n2\n26',
 "25\nCreepin'\nMetro Boomin, The Weeknd & 21 Savage\n33\n3\n40",
 '26\nBad Idea Right?\nOlivia Rodrigo\n35\n10\n4',
 '27\nMeltdown\nTravis Scott Featuring Drake\n36\n3\n6',
 '28\nDial Drunk\nNoah Kahan With Post Malone\n42\n25\n12',
 '29\nTourniquet\nZach Bryan\n20\n20\n2',
 '30\nTry That In A Small Town\nJason Aldean\n45\n1\n8',
 '31\nQlona\nKarol G & Peso Pluma\n43\n28\n4',
 '32\nLove You Anyway\nLuke Combs\n40\n15\n30',
 '33\nWatermelon Moonshine\nLainey Wilson\n46\n33\n11',
 '34\nI Know ?\nTravis Scott\n49\n11\n6',
 '35\nSpotless\nZach Bryan Featuring The Lumineers\n17\n17\n2',
 '36\nBury Me In Georgia\nKane Brown\n51\n34\n17',
 '37\nSeven\nJung Kook Featuring Latto\n28\n1\n8',
 '38\nRE- ENTRY\nMargaritaville\nJimmy Buffett\n-\n8\n23',
 '39\nSingle Soon\nSelena Gomez\n19\n19\n2',
 '40\nEast Side Of Sorrow\nZach Bryan\n18\n18\n2',
 '41\nWhat It Is (Block Boy)\nDoechii Featuring Kodak Black\n53\n41\n18',
 '42\nDaylight\nDavid Kushner\n52\n40\n21',
 '43\nMi Ex Tenia Razon\nKarol G\n50\n22\n4',
 '44\nLaLa\nMyke Towers\n54\n43\n9',
 '45\nCupid\nFifty Fifty\n48\n17\n25',
 '46\nNEW\nDemons\nDoja Cat\n-\n46\n1',
 '47\nLady Gaga\nPeso Pluma, Gabito Ballesteros & Junior H\n56\n35\n11',
 "48\nFear And Friday's\nZach Bryan\n24\n24\n2",
 '49\nEl Dorado\nZach Bryan\n31\n31\n2',
 '50\nTelekinesis\nTravis Scott Featuring SZA & Future\n55\n26\n6',
 '51\nPeaches & Eggplants\nYoung Nudy Featuring 21 Savage\n59\n49\n14',
 '52\nTicking\nZach Bryan\n29\n29\n2',
 "53\nSummertime's Close\nZach Bryan\n23\n23\n2",
 '54\nFE!N\nTravis Scott Featuring Playboi Carti\n58\n5\n6',
 '55\nOvertime\nZach Bryan\n22\n22\n2',
 '56\nNEW\nCome See Me\nRod Wave\n-\n56\n1',
 '57\nWhite Horse\nChris Stapleton\n63\n31\n7',
 '58\nGood Good\nUsher, Summer Walker & 21 Savage\n65\n58\n4',
 '59\nTruck Bed\nHARDY\n68\n55\n12',
 '60\nDeli\nIce Spice\n64\n41\n7',
 '61\nNEW\nQue Onda\nCalle 24 x Chino Pacas x Fuerza Regida\n-\n61\n1',
 '62\nStanding Room Only\nTim McGraw\n62\n61\n3',
 '63\nSmaller Acts\nZach Bryan\n38\n38\n2',
 '64\nEverything I Love\nMorgan Wallen\n73\n14\n28',
 '65\nIn Your Love\nTyler Childers\n83\n43\n6',
 '66\nPopular\nThe Weeknd, Playboi Carti & Madonna\n71\n43\n14',
 '67\nNEW\nSkeeYee\nSexyy Red\n-\n67\n1',
 '68\nPut It On Da Floor Again\nLatto Featuring Cardi B\n60\n13\n14',
 '69\nHoly Roller\nZach Bryan Featuring Sierra Ferrell\n37\n37\n2',
 '70\nSabor Fresa\nFuerza Regida\n74\n26\n11',
 '71\nTulum\nPeso Pluma & Grupo Frontera\n70\n43\n10',
 '72\nWhere She Goes\nBad Bunny\n66\n8\n16',
 "73\nAngels Don't Always Have Wings\nThomas Rhett\n77\n72\n7",
 '74\nK-POP\nTravis Scott, Bad Bunny & The Weeknd\n67\n7\n7',
 '75\nJohnny Dang\nThat Mexican OT, Paul Wall & DRODi\n75\n65\n8',
 '76\nOh U Went\nYoung Thug Featuring Drake\n81\n19\n11',
 '77\nDawns\nZach Bryan Featuring Maggie Rogers\n76\n42\n19',
 "78\nJake's Piano - Long Island\nZach Bryan\n41\n41\n2",
 '79\nSave Me\nJelly Roll With Lainey Wilson\n84\n70\n12',
 '80\nOklahoma Smoke Show\nZach Bryan\n88\n80\n7',
 '81\nLose Control\nTeddy Swims\n82\n81\n4',
 '82\nTradesman\nZach Bryan\n44\n44\n2',
 '83\nShake Sumn\nDaBaby\n78\n65\n16',
 '84\nNEW\nKeep Going Up!\nTimbaland, Nelly Furtado & Justin Timberlake\n-\n84\n1',
 '85\nArea Codes\nKaliii\n79\n33\n18',
 "86\nSittin' On Top Of The World\nBurna Boy\n80\n80\n2",
 '87\nPretty Little Poison\nWarren Zeiders\n92\n59\n4',
 '88\nOklahoman Son\nZach Bryan\n47\n47\n2',
 '89\nTQM\nFuerza Regida\n91\n34\n16',
 '90\nSee You Again\nTyler, The Creator Featuring Kali Uchis\n87\n44\n20',
 '91\nAmargura\nKarol G\n90\n85\n4',
 '92\nGirl In Mine\nParmalee\n99\n92\n6',
 '93\nRE- ENTRY\nEl Amor de Su Vida\nGrupo Frontera & Grupo Firme\n-\n82\n3',
 '94\nSummer Too Hot\nChris Brown\n96\n93\n3',
 '95\nRubicon\nPeso Pluma\n100\n63\n10',
 '96\nStand By Me\nLil Durk Featuring Morgan Wallen\n93\n22\n15',
 '97\nCall Your Friends\nRod Wave\n85\n26\n3',
 '98\nYour Heart Or Mine\nJon Pardi\n72\n47\n17',
 '99\nPrimera Cita\nCarin Leon\n97\n97\n2',
 '100\nS91\nKarol G\n86\n45\n6']

In [99]:
Song = []
Artist_name = []
Last_week_rank = []
Peak_rank = []
Weeks_on_board = []

for entry in Song_name:
    
    values = entry.split('\n')
    
    
    Song.append(values[1])
    Artist_name.append(values[2])
    Last_week_rank.append(values[3])
    Peak_rank.append(values[4])
    Weeks_on_board.append(values[5])

In [101]:
df5 =pd.DataFrame({'Song':Song,'Artist_name':Artist_name,'Last_week_rank':Last_week_rank,'Peak_rank':Peak_rank,'Weeks_on_board':Weeks_on_board})
df5

,Song,Artist_name,Last_week_rank,Peak_rank,Weeks_on_board
0,Paint The Town Red,Doja Cat,3,1,5
1,I Remember Everything,Zach Bryan Featuring Kacey Musgraves,1,1,2
2,Fast Car,Luke Combs,2,2,24
3,Cruel Summer,Taylor Swift,5,3,18
4,Last Night,Morgan Wallen,4,1,32
...,...,...,...,...,...
95,Stand By Me,Lil Durk Featuring Morgan Wallen,93,22,15
96,Call Your Friends,Rod Wave,85,26,3
97,Your Heart Or Mine,Jon Pardi,72,47,17
98,Primera Cita,Carin Leon,97,97,2
99,S91,Karol G,86,45,6

# ANS.6

In [20]:
driver = webdriver.Chrome()
driver.get("https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare")

In [22]:
Book_name = []
Author_name = []
Volumes_sold = []
Publisher = []
Genre = []

name= driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[2]')
for i in name:
    data = i.text
    Book_name.append(data)
    
a= driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[3]')
for i in a:
    data = i.text
    Author_name.append(data)

    
    v= driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[4]')
for i in v:
    data = i.text
    Volumes_sold.append(data)    

    
    p= driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[5]')
for i in p:
    data = i.text
    Publisher.append(data)    
    
g= driver.find_elements(By.XPATH,'//table[@class="in-article sortable"]/tbody/tr/td[6]')
for i in g:
    data = i.text
    Genre.append(data)

In [24]:
df6 = pd.DataFrame({'Book_name':Book_name,'Author_name':Author_name,'Volumes_sold':Volumes_sold,'Publisher':Publisher,'Genre':Genre})
df6

,Book_name,Author_name,Volumes_sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

# ANS.7

In [103]:
driver = webdriver.Chrome()
driver.get("https://www.imdb.com/list/ls095964455/")

In [124]:
ser_na = []

name= driver.find_elements(By.XPATH,'//div[@class="lister-item-content"]')
for i in name:
    data = i.text
    ser_na.append(data)

In [118]:
series_name_year = []
 
Genre_Run_time = []
Run_time = []
Ratings = []
Votes = []
for entry in ser_na:
    
    values = entry.split('\n')
    
    
    series_name_year.append(values[0])
    Genre_Run_time.append(values[1])
    Ratings.append(values[2])
    Votes.append(values[6])

In [122]:
Genre = []
Run_time = []


for item in Genre_Run_time:
    
    components = [part.strip() for part in item.split("|")]
    
    genre = components[2]
    runtime = components[1]
    
    
    Genre.append(genre)
    Run_time.append(runtime)

In [123]:
all_votes = [item.replace('Votes: ', '') for item in Votes ]

In [114]:
series_names = []
years = []
for item in series_name_year:
    
    parts = item.split('(')
    
    name = parts[0].split('. ')[1]  
    year = parts[1].rstrip(')')  

    
    series_names.append(name)
    years.append(year)

In [121]:
df7 = pd.DataFrame({'series_names':series_names,'years':years,'Genre':Genre,'Run_time':Run_time,'Ratings':Ratings,'all_votes':all_votes})
df7

,series_names,years,Genre,Run_time,Ratings,all_votes
0,Game of Thrones,2011–2019,"Action, Adventure, Drama",57 min,9.2,"2,203,266"
1,Stranger Things,2016–2025,"Drama, Fantasy, Horror",51 min,8.7,"1,275,027"
2,The Walking Dead,2010–2022,"Drama, Horror, Thriller",44 min,8.1,"1,045,450"
3,13 Reasons Why,2017–2020,"Drama, Mystery, Thriller",60 min,7.5,"307,255"
4,The 100,2014–2020,"Drama, Mystery, Sci-Fi",43 min,7.6,"266,359"
...,...,...,...,...,...,...
95,Reign,2013–2017,Drama,42 min,7.5,"52,706"
96,A Series of Unfortunate Events,2017–2019,"Adventure, Comedy, Drama",50 min,7.8,"64,757"
97,Criminal Minds,2005–,"Crime, Drama, Mystery",42 min,8.1,"210,969"
98,Scream: The TV Series,2015–2019,"Comedy, Crime, Drama",45 min,7,"43,885"
99,The Haunting of Hill House,2018,"Drama, Horror, Mystery",572 min,8.6,"265,765"

# ANS.8

In [5]:
driver = webdriver.Chrome()
driver.get("https://archive.ics.uci.edu/")

In [6]:
view_datasets =driver.find_element(By.XPATH,"/html/body/div/div[1]/div[1]/main/div/div[1]/div/div/div/a[1]")
view_datasets.click()

In [8]:
row_page =driver.find_element(By.XPATH,'//select[@class="select-primary select select-sm rounded-full"]/option[5]')
row_page.click()

In [15]:
datasets_url =[]
start = 0
end = 26
for page in range (start,end):
    url = driver.find_elements(By.XPATH,'//a[@class="link-hover link text-xl font-semibold"]')
    for i in url:
        datasets_url.append(i.get_attribute('href'))
    next_button=driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[2]/div[3]/div/button[2]')    
    next_button.click()
    time.sleep(1)

ElementClickInterceptedException: Message: element click intercepted: Element <button class="btn-primary btn-sm btn" aria-label="Next Page" disabled="">...</button> is not clickable at point (754, 474). Other element would receive the click: <div class="btn-group">...</div>
  (Session info: chrome=116.0.5845.189)
Stacktrace:
	GetHandleVerifier [0x00007FF6691552A2+57122]
	(No symbol) [0x00007FF6690CEA92]
	(No symbol) [0x00007FF668F9E3AB]
	(No symbol) [0x00007FF668FDD783]
	(No symbol) [0x00007FF668FDBD5F]
	(No symbol) [0x00007FF668FD9DC8]
	(No symbol) [0x00007FF668FD8FD5]
	(No symbol) [0x00007FF668FCF25F]
	(No symbol) [0x00007FF668FF6FDA]
	(No symbol) [0x00007FF668FCEB76]
	(No symbol) [0x00007FF668FF71F0]
	(No symbol) [0x00007FF66900EB82]
	(No symbol) [0x00007FF668FF6DB3]
	(No symbol) [0x00007FF668FCD2B1]
	(No symbol) [0x00007FF668FCE494]
	GetHandleVerifier [0x00007FF6693FEF82+2849794]
	GetHandleVerifier [0x00007FF669451D24+3189156]
	GetHandleVerifier [0x00007FF66944ACAF+3160367]
	GetHandleVerifier [0x00007FF6691E6D06+653702]
	(No symbol) [0x00007FF6690DA208]
	(No symbol) [0x00007FF6690D62C4]
	(No symbol) [0x00007FF6690D63F6]
	(No symbol) [0x00007FF6690C67A3]
	BaseThreadInitThunk [0x00007FF8DD2F7344+20]
	RtlUserThreadStart [0x00007FF8DF0626B1+33]

In [17]:
len(datasets_url)

649

In [18]:
Dataset_name = []
Data_type = []
Task = []
Attribute_type = []
No_of_instances = []
No_of_attribute = []
Year = []

for i in datasets_url:
    driver.get(i)
    time.sleep(1)
    try:
        Name =driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[1]/div[1]/div[1]/div[2]/div/h1')
        Dataset_name.append(Name.text)
    except NoSuchElementException:
        Dataset_name.append('Not present')
        


    try:
        Data =driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[1]/div[1]/div[2]/div[2]/div[1]/p')
        Data_type.append(Data.text)
    except NoSuchElementException:
        Data_type.append('Not present')
        
        
        

    try:
        t =driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[1]/div[1]/div[2]/div[2]/div[3]/p')
        Task.append(t.text)
    except NoSuchElementException:
        Task.append('Not present')    
        
        
        


    try:
        a =driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[1]/div[1]/div[2]/div[2]/div[4]/p')
        Attribute_type.append(a.text)
    except NoSuchElementException:
        Attribute_type.append('Not present')     
        
        
        
    try:
        no =driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[1]/div[1]/div[2]/div[2]/div[5]/p')
        No_of_instances.append(no.text)
    except NoSuchElementException:
        No_of_instances.append('Not present')        
        
        
        
    try:
        no_of =driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[1]/div[1]/div[2]/div[2]/div[6]/p')
        No_of_attribute.append(no_of.text)
    except NoSuchElementException:
        No_of_attribute.append('Not present')  
        
      
    
    try:
        yy =driver.find_element(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[1]/div[1]/div[1]/div[2]/h2')
        Year.append(yy.text)
    except NoSuchElementException:
        Year.append('Not present')

In [20]:
df8 = pd.DataFrame({'Dataset_name':Dataset_name,'Data_type':Data_type,'Task':Task,'Attribute_type':Attribute_type,'No_of_instances':No_of_instances,'No_of_attribute':No_of_attribute,'Year':Year})
df8

,Dataset_name,Data_type,Task,Attribute_type,No_of_instances,No_of_attribute,Year
0,Iris,Tabular,Classification,Real,150,4,Donated on 6/30/1988
1,Heart Disease,Multivariate,Classification,"Categorical, Integer, Real",303,13,Donated on 6/30/1988
2,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,Donated on 4/30/1996
3,Dry Bean Dataset,Multivariate,Classification,"Integer, Real",13611,16,Donated on 9/13/2020
4,Diabetes,"Multivariate, Time-Series",-,"Categorical, Integer",-,20,Not present
...,...,...,...,...,...,...,...
644,Average Localization Error (ALE) in sensor nod...,Multivariate,Regression,Real,107,4,Donated on 8/13/2023
645,TamilSentiMix,"Multivariate, Text",Classification,Categorical,15744,-,Donated on 8/13/2023
646,MOVER: Medical Informatics Operating Room Vita...,"Tabular, Sequential, Multivariate, Time-Series","Classification, Regression, Clustering, Other",-,83468,-,Linked on 9/8/2023
647,Cirrhosis Patient Survival Prediction Dataset,Tabular,Classification,"Real, Categorical",418,18,Donated on 9/11/2023
648,Visegrad Group companies data,Multivariate,"Classification, Clustering",Real,85,83,Donated on 7/16/2023